DATA SEGMENT
MES DB 'Show a as hex:',0AH,0DH,'$'
SD DB 'a'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
MOV DS,AX
MOV DX,OFFSET MES ;显示提示信息
MOV AH,09H
INT 21H
 MOV SI,OFFSET SD
 MOV AL,DS:[SI]
 AND AL,0F0H ;取高4位
MOV CL,4
 SHR AL,CL
 CMP AL,0AH ;是否是A以上的数
 JB C2
 ADD AL,07H
C2: ADD AL,30H
 MOV DL,AL ;显示字符
 MOV AH,02H
 INT 21H
 MOV AL,DS:[SI]
 AND AL,0FH ;取低4位
 CMP AL,0AH
 JB C3
 ADD AL,07H
C3: ADD AL,30H
 MOV DL,AL ;显示字符
 MOV AH,02H
 INT 21H
 MOV AH,4CH ;返回DOS
 INT 21H
CODE ENDS
END START